name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Flet and Dependencies
        run: |
          pip install flet
          # تثبيت أدوات أندرويد اللازمة يدوياً لضمان عدم وجود نقص
          pip install flet[all] 

      - name: Build APK
        run: |
          # الأمر ده هو اللي بيقوم بالليلة كلها وبيوافق على الرخص لوحده
          flet build apk --no-interactive
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FreshMarketApp
          path: build/apk/*.apk
